version: '3.8'

services:
  vpnTgBot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpnTgBot
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - usersdb:/app/data
    networks:
      - vpnTgBot-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org/bot${BOT_TOKEN}/getMe', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  vpnTgBot-network:
    driver: bridge

volumes:
  usersdb: